### PR TITLE
Signaling tests

### PR DESCRIPTION
**Pull request by aullman**
Adding tests for the Signaling Sample Application

### CODE REVIEW

**Comment by aullman** [comment]
safari stable failed errorShot

**Comment by aullman** [comment]
firefox stable failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by msach22** [comment]
@aullman looks like the travis build failed: https://cl.ly/1G1B1M292t1H

**Comment by aullman** [comment]
Hm, yeah, that's the Vue app test failing in Safari. I'm going to re-run it.

**Comment by aullman** [comment]
@msach22 yeah, it passed this time. Not sure what the problem was.

**Comment by msach22** [comment]
@aullman awesome thanks!

**Pull request merged**
