### PR TITLE
Adding tests for Vue-Basic-Video-Chat

### PR DESCRIPTION
**Pull request by aullman**

### CODE REVIEW

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by msach22** [comment]
@aullman It looks like this PR has the Basic-Video-Chat test in it as well, is that intentional or is it just supposed to be for Vue?

**Comment by aullman** [comment]
@msach22 yeah, that's intentional. While writing the test for this sample I realised that there was a better way to do some of the things in the basic samples tests as well.

**Pull request merged**
