### PR TITLE
Migrating to Angular 6

### PR DESCRIPTION
**Pull request by aullman**
Migrating the angular sample application to use Angular 6.

### CODE REVIEW

**Comment by aullman** [comment]
chrome stable failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
chrome stable failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
chrome stable failed errorShot

**Comment by aullman** [comment]
safari stable failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
ie 11 failed errorShot

**Comment by aullman** [comment]
safari stable failed errorShot

**Comment by aullman** [comment]
chrome stable failed errorShot

**Comment by aullman** [comment]
safari stable failed errorShot

**Comment by msach22** [comment]
@aullman are the APIs the same for using Angular 6 v Angular 5? JW because I didn't see any code changes 😄

**Comment by aullman** [comment]
@msach22 yeah, no changes necessary. I actually used `npm update @angular/cli` and it handled all of the migration. The only difference was config changes.

**Pull request merged**
